main: functionality.Main
version: 0.0.8
name: LockCraft

commands:
  modifypin:
    description: Modify your pin.
  lc-reload:
    description: Reload the plugin.
  lc-help:
    description: Command to see all the plugin information.